"""Power-management foundation for InstantLink Bridge."""

from instantlink_bridge.power.monitor import (
    BatteryAlert,
    BatteryClient,
    BatteryEvaluation,
    BatteryPolicy,
    Clock,
    IdlePolicy,
    IdleStage,
    IdleState,
    IdleTimer,
    IdleTransition,
    MonotonicClock,
    PowerEvent,
    PowerEventHandler,
    PowerEventKind,
    PowerMonitor,
    PowerPolicy,
    ShutdownCallable,
    ShutdownReason,
    evaluate_battery,
)
from instantlink_bridge.power.pisugar import (
    BATTERY_STATE_COMMANDS,
    DEFAULT_SOCKET_PATH,
    BatteryState,
    PiSugarClient,
    PiSugarError,
    PiSugarProtocolError,
    PiSugarResponse,
    PiSugarSocketUnavailable,
    PiSugarTransport,
    UnixSocketPiSugarTransport,
    parse_pisugar_response,
)
from instantlink_bridge.power.x306 import NoBatteryClient, X306BatteryClient

__all__ = [
    "BATTERY_STATE_COMMANDS",
    "DEFAULT_SOCKET_PATH",
    "BatteryAlert",
    "BatteryClient",
    "BatteryEvaluation",
    "BatteryPolicy",
    "BatteryState",
    "Clock",
    "IdlePolicy",
    "IdleStage",
    "IdleState",
    "IdleTimer",
    "IdleTransition",
    "MonotonicClock",
    "NoBatteryClient",
    "PiSugarClient",
    "PiSugarError",
    "PiSugarProtocolError",
    "PiSugarResponse",
    "PiSugarSocketUnavailable",
    "PiSugarTransport",
    "PowerEvent",
    "PowerEventHandler",
    "PowerEventKind",
    "PowerMonitor",
    "PowerPolicy",
    "ShutdownCallable",
    "ShutdownReason",
    "UnixSocketPiSugarTransport",
    "X306BatteryClient",
    "evaluate_battery",
    "parse_pisugar_response",
]
